spring.config.import=optional:file:.env[.properties]
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=journalDb
spring.data.mongodb.auto-index-creation=true
weather.api.key=${WEATHER_API_KEY}