spring:
    config:
        import: optional:file:.env[.properties]
    mongodb:
        uri: ${MONGODB_URI}
        database: journalDb
    data:
        mongodb:
            auto-index-creation: true
        redis:
            url: ${REDIS_URI}
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL_USERNAME}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    kafka:
        bootstrap-servers: ${KAFKA_SERVER}
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
            group-id: weekly-sentiment-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring:
                    json:
                        trusted:
                            packages: "*"
        properties:
            session:
                timeout:
                    ms: 45000
            security:
                protocol: SASL_SSL
            sasl:
                mechanism: PLAIN
                jaas:
                    config: ${KAFKA_CONFIG}

weather:
    api:
        key: ${WEATHER_API_KEY}


client:
    id: ${KAFKA_CLIENT_ID}





